# Generated by Django 5.1.6 on 2025-02-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='Record',
        ),
    ]
