# Generated by Django 5.1.6 on 2025-02-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='record',
        ),
    ]
